services:
  weaviate:
    image: semitechnologies/weaviate:latest
    restart: always
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "./weaviate_data"
      ENABLE_MODULES: "text2vec-openai"
      WEAVIATE_OPENAI_API_KEY: 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

    volumes:
      - "./weaviate_data:/var/lib/weaviate"
    depends_on:
      - db

  langfuse:
    image: ghcr.io/langfuse/langfuse:latest
    restart: always
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: mysecret
      SALT: mysalt
    ports:
      - "3000:3000"
    depends_on:
      - db
      - weaviate  # Ensure langfuse depends on weaviate if necessary

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
